### ISSUE TITLE
Yii 1.1 Functions/Methods

### ISSUE THREAD

**Issue by mmx3** [spanjeta/yii2-backup#3]
You probably have 1.1 installed and in your Path so it's working for you. CHtml, CHttpException, and CUploadedFile need to be changed to the 2.x equivalents.

The use statements for the applicable files need to be included in the controller. 

yii\web\HttpException
yii\web\UploadedFile
yii\helpers\Html

**Comment by spanjeta** [comment]
Thank you so much for sharing. yes, this extension is upgrade of 1.1.  I would update it soon.

**Comment by eduardo-g-silva** [comment]
Changes for the backup extension

\vendor\spanjeta\yii2-backup\controllers\DefaultController.php
before 
class DefaultController extends Controller

add
use yii\web\HttpException;
use yii\web\UploadedFile;
use yii\helpers\Html;

arrownd line 321 at public function actionUpload()
change
$model->upload_file = CUploadedFile::getInstance($model,'upload_file');
 with
$model->upload_file = UploadedFile::getInstance($model,'upload_file');


still fighting with the 
        array(
            'class' => 'yii\grid\ActionColumn',
            'template' => '{restore}',
        ),

**Comment by mmx3** [comment]
Thanks for the update! 

Did some testing earlier by importing a 115 table backup into phpMyAdmin, then reverse engineered the resulting database using MySQL Workbench to take a look at how it handled the constraints. A number of tables have One- to- Many or Many-to-Many relationships and I found no problems. 

Was going to take a look at the 1.1 version to see if I could isolate the one other problem experienced, but it looks like you are following up on the problem.

**Comment by mtangoo** [comment]
Your extension page is confusing. Please make clear what have been ported and what remains.
That will even encourage others to help finish it up!

**Comment by spanjeta** [comment]
Thank you so much for writing . My busy schedule kept me away and delayed the changes. I am surprised to see so many mistakes and left over code. I must stopped working late night :-).
I have fixed these issues a new version would be coming soon. Thanks.

**Comment by eduardo-g-silva** [comment]
Hi Spanjeta we did the changes and change some things we need it you can have a look if you plan to modify yours
https://github.com/open-ecommerce/yii2-backuprestore 

Regards,

Eduardo

**Comment by mtangoo** [comment]
@eduardo-g-silva why not do a PR?

**Comment by eduardo-g-silva** [comment]
because i made too many changes, remove the menu and add many external
extentions

   *Eduardo Silva*
Director
*open-ecommerce.org <http://open-ecommerce.org>*

​Unit 23A Iliffe Yard,
London, SE17 3QA
m: 07551524625

Website    <http://open-ecommerce.org>|   Email
<eduardo@open-ecommerce.org>|   Twitter
<http://twitter.com/@eduardo_g_silva>



Registered in England and Wales No 8897268.



Any views or opinions presented are solely those of the author and do not
necessarily represent those of Open-ecommerce.org. Access is authorized by
the intended recipient only.
