### ISSUE TITLE
Add flash messages and file extension validation

### ISSUE THREAD

**Issue by AlexMcowkin** [spanjeta/yii2-backup#8]
Hello!

Thank you for your extension.

Can you make some modification of your DefaultController.php ???
1. in actionCreate after $this->EndBackup();
   please add Yii::$app->session->setFlash('success', "Data saved!");
2. in actionDelete before return $this->actionIndex();
   please add Yii::$app->session->setFlash('success', "Data deleted!");
3. in actionUpload before redirect to success page
   please add Yii::$app->session->setFlash('success', "Data uploaded!");

Also it would be good if you add file extension validation in UploadForm.php
[['file'], 'file', 'extensions' => 'sql'],

thank you

**Comment by spanjeta** [comment]
Thank you so much. 
Im merging it today.
