### ISSUE TITLE
Database Exception – yii\db\Exception - Postgresql

### ISSUE THREAD

**Issue by sciefylab** [spanjeta/yii2-backup#9]
Hi,

I have an error bellow when create backup, I used postgresql.

`Database Exception – yii\db\Exception

SQLSTATE[42704]: Undefined object: 7 ERROR: unrecognized configuration parameter "tables"
The SQL being executed was: SHOW TABLES
Error Info: Array
(
    [0] => 42704
    [1] => 7
    [2] => ERROR:  unrecognized configuration parameter "tables"
)
↵
Caused by: PDOException

SQLSTATE[42704]: Undefined object: 7 ERROR: unrecognized configuration parameter "tables"`

help please,

thanks
Rino

**Comment by spanjeta** [comment]
Thanks for reporting. Currently we only support MySQL.
